// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/grimnirfanout/v1/grimnirfanout.proto

package grimnirfanoutv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveSessions int64                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	// Aggregate count of currently active DJ sessions (sum of per-protocol).
	HarborSessionCount  int64 `protobuf:"varint,4,opt,name=harbor_session_count,json=harborSessionCount,proto3" json:"harbor_session_count,omitempty"`
	RtpSessionCount     int64 `protobuf:"varint,5,opt,name=rtp_session_count,json=rtpSessionCount,proto3" json:"rtp_session_count,omitempty"`
	SrtSessionCount     int64 `protobuf:"varint,6,opt,name=srt_session_count,json=srtSessionCount,proto3" json:"srt_session_count,omitempty"`
	WebrtcSessionCount  int64 `protobuf:"varint,7,opt,name=webrtc_session_count,json=webrtcSessionCount,proto3" json:"webrtc_session_count,omitempty"`
	TotalSessionsServed int64 `protobuf:"varint,8,opt,name=total_sessions_served,json=totalSessionsServed,proto3" json:"total_sessions_served,omitempty"`
	// Per-engine RTP reachability as reported by the fan-out's own probe layer.
	EngineAReachable bool `protobuf:"varint,9,opt,name=engine_a_reachable,json=engineAReachable,proto3" json:"engine_a_reachable,omitempty"`
	EngineBReachable bool `protobuf:"varint,10,opt,name=engine_b_reachable,json=engineBReachable,proto3" json:"engine_b_reachable,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *StatusResponse) GetHarborSessionCount() int64 {
	if x != nil {
		return x.HarborSessionCount
	}
	return 0
}

func (x *StatusResponse) GetRtpSessionCount() int64 {
	if x != nil {
		return x.RtpSessionCount
	}
	return 0
}

func (x *StatusResponse) GetSrtSessionCount() int64 {
	if x != nil {
		return x.SrtSessionCount
	}
	return 0
}

func (x *StatusResponse) GetWebrtcSessionCount() int64 {
	if x != nil {
		return x.WebrtcSessionCount
	}
	return 0
}

func (x *StatusResponse) GetTotalSessionsServed() int64 {
	if x != nil {
		return x.TotalSessionsServed
	}
	return 0
}

func (x *StatusResponse) GetEngineAReachable() bool {
	if x != nil {
		return x.EngineAReachable
	}
	return false
}

func (x *StatusResponse) GetEngineBReachable() bool {
	if x != nil {
		return x.EngineBReachable
	}
	return false
}

var File_proto_grimnirfanout_v1_grimnirfanout_proto protoreflect.FileDescriptor

const file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDesc = "" +
	"\n" +
	"*proto/grimnirfanout/v1/grimnirfanout.proto\x12\x10grimnirfanout.v1\"\x0f\n" +
	"\rStatusRequest\"\xc6\x03\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x03R\x0eactiveSessions\x120\n" +
	"\x14harbor_session_count\x18\x04 \x01(\x03R\x12harborSessionCount\x12*\n" +
	"\x11rtp_session_count\x18\x05 \x01(\x03R\x0frtpSessionCount\x12*\n" +
	"\x11srt_session_count\x18\x06 \x01(\x03R\x0fsrtSessionCount\x120\n" +
	"\x14webrtc_session_count\x18\a \x01(\x03R\x12webrtcSessionCount\x122\n" +
	"\x15total_sessions_served\x18\b \x01(\x03R\x13totalSessionsServed\x12,\n" +
	"\x12engine_a_reachable\x18\t \x01(\bR\x10engineAReachable\x12,\n" +
	"\x12engine_b_reachable\x18\n" +
	" \x01(\bR\x10engineBReachable2_\n" +
	"\rGrimnirFanout\x12N\n" +
	"\tGetStatus\x12\x1f.grimnirfanout.v1.StatusRequest\x1a .grimnirfanout.v1.StatusResponseBOZMgithub.com/friendsincode/grimnir_radio/proto/grimnirfanout/v1;grimnirfanoutv1b\x06proto3"

var (
	file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescOnce sync.Once
	file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescData []byte
)

func file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescGZIP() []byte {
	file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescOnce.Do(func() {
		file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDesc), len(file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDesc)))
	})
	return file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDescData
}

var file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grimnirfanout_v1_grimnirfanout_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: grimnirfanout.v1.StatusRequest
	(*StatusResponse)(nil), // 1: grimnirfanout.v1.StatusResponse
}
var file_proto_grimnirfanout_v1_grimnirfanout_proto_depIdxs = []int32{
	0, // 0: grimnirfanout.v1.GrimnirFanout.GetStatus:input_type -> grimnirfanout.v1.StatusRequest
	1, // 1: grimnirfanout.v1.GrimnirFanout.GetStatus:output_type -> grimnirfanout.v1.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grimnirfanout_v1_grimnirfanout_proto_init() }
func file_proto_grimnirfanout_v1_grimnirfanout_proto_init() {
	if File_proto_grimnirfanout_v1_grimnirfanout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDesc), len(file_proto_grimnirfanout_v1_grimnirfanout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grimnirfanout_v1_grimnirfanout_proto_goTypes,
		DependencyIndexes: file_proto_grimnirfanout_v1_grimnirfanout_proto_depIdxs,
		MessageInfos:      file_proto_grimnirfanout_v1_grimnirfanout_proto_msgTypes,
	}.Build()
	File_proto_grimnirfanout_v1_grimnirfanout_proto = out.File
	file_proto_grimnirfanout_v1_grimnirfanout_proto_goTypes = nil
	file_proto_grimnirfanout_v1_grimnirfanout_proto_depIdxs = nil
}
