// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/grimnirfanout/v1/grimnirfanout.proto

package grimnirfanoutv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrimnirFanout_GetStatus_FullMethodName = "/grimnirfanout.v1.GrimnirFanout/GetStatus"
)

// GrimnirFanoutClient is the client API for GrimnirFanout service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrimnirFanout exposes operational status of a fan-out instance. Mirrors the
// EdgeEncoder service convention: control plane scrapes GetStatus instead of
// the standard grpc.health.v1 Health protocol.
type GrimnirFanoutClient interface {
	// GetStatus returns the current operational state of the fan-out service.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type grimnirFanoutClient struct {
	cc grpc.ClientConnInterface
}

func NewGrimnirFanoutClient(cc grpc.ClientConnInterface) GrimnirFanoutClient {
	return &grimnirFanoutClient{cc}
}

func (c *grimnirFanoutClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, GrimnirFanout_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrimnirFanoutServer is the server API for GrimnirFanout service.
// All implementations must embed UnimplementedGrimnirFanoutServer
// for forward compatibility.
//
// GrimnirFanout exposes operational status of a fan-out instance. Mirrors the
// EdgeEncoder service convention: control plane scrapes GetStatus instead of
// the standard grpc.health.v1 Health protocol.
type GrimnirFanoutServer interface {
	// GetStatus returns the current operational state of the fan-out service.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedGrimnirFanoutServer()
}

// UnimplementedGrimnirFanoutServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrimnirFanoutServer struct{}

func (UnimplementedGrimnirFanoutServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedGrimnirFanoutServer) mustEmbedUnimplementedGrimnirFanoutServer() {}
func (UnimplementedGrimnirFanoutServer) testEmbeddedByValue()                       {}

// UnsafeGrimnirFanoutServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrimnirFanoutServer will
// result in compilation errors.
type UnsafeGrimnirFanoutServer interface {
	mustEmbedUnimplementedGrimnirFanoutServer()
}

func RegisterGrimnirFanoutServer(s grpc.ServiceRegistrar, srv GrimnirFanoutServer) {
	// If the following call panics, it indicates UnimplementedGrimnirFanoutServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrimnirFanout_ServiceDesc, srv)
}

func _GrimnirFanout_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrimnirFanoutServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrimnirFanout_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrimnirFanoutServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrimnirFanout_ServiceDesc is the grpc.ServiceDesc for GrimnirFanout service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrimnirFanout_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grimnirfanout.v1.GrimnirFanout",
	HandlerType: (*GrimnirFanoutServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _GrimnirFanout_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/grimnirfanout/v1/grimnirfanout.proto",
}
