/*
Copyright (C) 2026 Friends Incode

SPDX-License-Identifier: AGPL-3.0-or-later
*/


// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/mediaengine/v1/mediaengine.proto

package mediaenginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNSPECIFIED SourceType = 0
	SourceType_SOURCE_TYPE_MEDIA       SourceType = 1
	SourceType_SOURCE_TYPE_WEBSTREAM   SourceType = 2
	SourceType_SOURCE_TYPE_LIVE        SourceType = 3
	SourceType_SOURCE_TYPE_FALLBACK    SourceType = 4
	SourceType_SOURCE_TYPE_EMERGENCY   SourceType = 5
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_MEDIA",
		2: "SOURCE_TYPE_WEBSTREAM",
		3: "SOURCE_TYPE_LIVE",
		4: "SOURCE_TYPE_FALLBACK",
		5: "SOURCE_TYPE_EMERGENCY",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_MEDIA":       1,
		"SOURCE_TYPE_WEBSTREAM":   2,
		"SOURCE_TYPE_LIVE":        3,
		"SOURCE_TYPE_FALLBACK":    4,
		"SOURCE_TYPE_EMERGENCY":   5,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mediaengine_v1_mediaengine_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_proto_mediaengine_v1_mediaengine_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{0}
}

type LiveInputType int32

const (
	LiveInputType_LIVE_INPUT_TYPE_UNSPECIFIED LiveInputType = 0
	LiveInputType_LIVE_INPUT_TYPE_ICECAST     LiveInputType = 1 // Icecast/HTTP source
	LiveInputType_LIVE_INPUT_TYPE_RTP         LiveInputType = 2 // RTP/UDP stream
	LiveInputType_LIVE_INPUT_TYPE_SRT         LiveInputType = 3 // Secure Reliable Transport
	LiveInputType_LIVE_INPUT_TYPE_WEBRTC      LiveInputType = 4 // WebRTC stream
)

// Enum value maps for LiveInputType.
var (
	LiveInputType_name = map[int32]string{
		0: "LIVE_INPUT_TYPE_UNSPECIFIED",
		1: "LIVE_INPUT_TYPE_ICECAST",
		2: "LIVE_INPUT_TYPE_RTP",
		3: "LIVE_INPUT_TYPE_SRT",
		4: "LIVE_INPUT_TYPE_WEBRTC",
	}
	LiveInputType_value = map[string]int32{
		"LIVE_INPUT_TYPE_UNSPECIFIED": 0,
		"LIVE_INPUT_TYPE_ICECAST":     1,
		"LIVE_INPUT_TYPE_RTP":         2,
		"LIVE_INPUT_TYPE_SRT":         3,
		"LIVE_INPUT_TYPE_WEBRTC":      4,
	}
)

func (x LiveInputType) Enum() *LiveInputType {
	p := new(LiveInputType)
	*p = x
	return p
}

func (x LiveInputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LiveInputType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mediaengine_v1_mediaengine_proto_enumTypes[1].Descriptor()
}

func (LiveInputType) Type() protoreflect.EnumType {
	return &file_proto_mediaengine_v1_mediaengine_proto_enumTypes[1]
}

func (x LiveInputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LiveInputType.Descriptor instead.
func (LiveInputType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{1}
}

type PlaybackState int32

const (
	PlaybackState_PLAYBACK_STATE_UNSPECIFIED PlaybackState = 0
	PlaybackState_PLAYBACK_STATE_IDLE        PlaybackState = 1
	PlaybackState_PLAYBACK_STATE_LOADING     PlaybackState = 2
	PlaybackState_PLAYBACK_STATE_PLAYING     PlaybackState = 3
	PlaybackState_PLAYBACK_STATE_FADING      PlaybackState = 4
	PlaybackState_PLAYBACK_STATE_PAUSED      PlaybackState = 5
	PlaybackState_PLAYBACK_STATE_ERROR       PlaybackState = 6
)

// Enum value maps for PlaybackState.
var (
	PlaybackState_name = map[int32]string{
		0: "PLAYBACK_STATE_UNSPECIFIED",
		1: "PLAYBACK_STATE_IDLE",
		2: "PLAYBACK_STATE_LOADING",
		3: "PLAYBACK_STATE_PLAYING",
		4: "PLAYBACK_STATE_FADING",
		5: "PLAYBACK_STATE_PAUSED",
		6: "PLAYBACK_STATE_ERROR",
	}
	PlaybackState_value = map[string]int32{
		"PLAYBACK_STATE_UNSPECIFIED": 0,
		"PLAYBACK_STATE_IDLE":        1,
		"PLAYBACK_STATE_LOADING":     2,
		"PLAYBACK_STATE_PLAYING":     3,
		"PLAYBACK_STATE_FADING":      4,
		"PLAYBACK_STATE_PAUSED":      5,
		"PLAYBACK_STATE_ERROR":       6,
	}
)

func (x PlaybackState) Enum() *PlaybackState {
	p := new(PlaybackState)
	*p = x
	return p
}

func (x PlaybackState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mediaengine_v1_mediaengine_proto_enumTypes[2].Descriptor()
}

func (PlaybackState) Type() protoreflect.EnumType {
	return &file_proto_mediaengine_v1_mediaengine_proto_enumTypes[2]
}

func (x PlaybackState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackState.Descriptor instead.
func (PlaybackState) EnumDescriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{2}
}

type FadeCurve int32

const (
	FadeCurve_FADE_CURVE_UNSPECIFIED FadeCurve = 0
	FadeCurve_FADE_CURVE_LINEAR      FadeCurve = 1
	FadeCurve_FADE_CURVE_LOGARITHMIC FadeCurve = 2
	FadeCurve_FADE_CURVE_EXPONENTIAL FadeCurve = 3
	FadeCurve_FADE_CURVE_SCURVE      FadeCurve = 4 // S-curve (smooth)
)

// Enum value maps for FadeCurve.
var (
	FadeCurve_name = map[int32]string{
		0: "FADE_CURVE_UNSPECIFIED",
		1: "FADE_CURVE_LINEAR",
		2: "FADE_CURVE_LOGARITHMIC",
		3: "FADE_CURVE_EXPONENTIAL",
		4: "FADE_CURVE_SCURVE",
	}
	FadeCurve_value = map[string]int32{
		"FADE_CURVE_UNSPECIFIED": 0,
		"FADE_CURVE_LINEAR":      1,
		"FADE_CURVE_LOGARITHMIC": 2,
		"FADE_CURVE_EXPONENTIAL": 3,
		"FADE_CURVE_SCURVE":      4,
	}
)

func (x FadeCurve) Enum() *FadeCurve {
	p := new(FadeCurve)
	*p = x
	return p
}

func (x FadeCurve) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FadeCurve) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mediaengine_v1_mediaengine_proto_enumTypes[3].Descriptor()
}

func (FadeCurve) Type() protoreflect.EnumType {
	return &file_proto_mediaengine_v1_mediaengine_proto_enumTypes[3]
}

func (x FadeCurve) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FadeCurve.Descriptor instead.
func (FadeCurve) EnumDescriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{3}
}

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED        NodeType = 0
	NodeType_NODE_TYPE_INPUT              NodeType = 1
	NodeType_NODE_TYPE_OUTPUT             NodeType = 2
	NodeType_NODE_TYPE_LOUDNESS_NORMALIZE NodeType = 3
	NodeType_NODE_TYPE_AGC                NodeType = 4
	NodeType_NODE_TYPE_COMPRESSOR         NodeType = 5
	NodeType_NODE_TYPE_LIMITER            NodeType = 6
	NodeType_NODE_TYPE_EQUALIZER          NodeType = 7
	NodeType_NODE_TYPE_GATE               NodeType = 8
	NodeType_NODE_TYPE_SILENCE_DETECTOR   NodeType = 9
	NodeType_NODE_TYPE_LEVEL_METER        NodeType = 10
	NodeType_NODE_TYPE_MIX                NodeType = 11
	NodeType_NODE_TYPE_DUCK               NodeType = 12 // Audio ducking
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0:  "NODE_TYPE_UNSPECIFIED",
		1:  "NODE_TYPE_INPUT",
		2:  "NODE_TYPE_OUTPUT",
		3:  "NODE_TYPE_LOUDNESS_NORMALIZE",
		4:  "NODE_TYPE_AGC",
		5:  "NODE_TYPE_COMPRESSOR",
		6:  "NODE_TYPE_LIMITER",
		7:  "NODE_TYPE_EQUALIZER",
		8:  "NODE_TYPE_GATE",
		9:  "NODE_TYPE_SILENCE_DETECTOR",
		10: "NODE_TYPE_LEVEL_METER",
		11: "NODE_TYPE_MIX",
		12: "NODE_TYPE_DUCK",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED":        0,
		"NODE_TYPE_INPUT":              1,
		"NODE_TYPE_OUTPUT":             2,
		"NODE_TYPE_LOUDNESS_NORMALIZE": 3,
		"NODE_TYPE_AGC":                4,
		"NODE_TYPE_COMPRESSOR":         5,
		"NODE_TYPE_LIMITER":            6,
		"NODE_TYPE_EQUALIZER":          7,
		"NODE_TYPE_GATE":               8,
		"NODE_TYPE_SILENCE_DETECTOR":   9,
		"NODE_TYPE_LEVEL_METER":        10,
		"NODE_TYPE_MIX":                11,
		"NODE_TYPE_DUCK":               12,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mediaengine_v1_mediaengine_proto_enumTypes[4].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_proto_mediaengine_v1_mediaengine_proto_enumTypes[4]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{4}
}

// LoadGraphRequest contains DSP graph configuration
type LoadGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Graph         *DSPGraph              `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGraphRequest) Reset() {
	*x = LoadGraphRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGraphRequest) ProtoMessage() {}

func (x *LoadGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGraphRequest.ProtoReflect.Descriptor instead.
func (*LoadGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{0}
}

func (x *LoadGraphRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *LoadGraphRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *LoadGraphRequest) GetGraph() *DSPGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type LoadGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraphHandle   string                 `protobuf:"bytes,1,opt,name=graph_handle,json=graphHandle,proto3" json:"graph_handle,omitempty"` // Unique identifier for the loaded graph
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGraphResponse) Reset() {
	*x = LoadGraphResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGraphResponse) ProtoMessage() {}

func (x *LoadGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGraphResponse.ProtoReflect.Descriptor instead.
func (*LoadGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{1}
}

func (x *LoadGraphResponse) GetGraphHandle() string {
	if x != nil {
		return x.GraphHandle
	}
	return ""
}

func (x *LoadGraphResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadGraphResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PlayRequest initiates playback
type PlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Source        *SourceConfig          `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CuePoints     *CuePoints             `protobuf:"bytes,4,opt,name=cue_points,json=cuePoints,proto3" json:"cue_points,omitempty"`
	Fade          *FadeConfig            `protobuf:"bytes,5,opt,name=fade,proto3" json:"fade,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"` // Priority level (0-4)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayRequest) Reset() {
	*x = PlayRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayRequest) ProtoMessage() {}

func (x *PlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayRequest.ProtoReflect.Descriptor instead.
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{2}
}

func (x *PlayRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *PlayRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *PlayRequest) GetSource() *SourceConfig {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PlayRequest) GetCuePoints() *CuePoints {
	if x != nil {
		return x.CuePoints
	}
	return nil
}

func (x *PlayRequest) GetFade() *FadeConfig {
	if x != nil {
		return x.Fade
	}
	return nil
}

func (x *PlayRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type PlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PlaybackId    string                 `protobuf:"bytes,2,opt,name=playback_id,json=playbackId,proto3" json:"playback_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayResponse) Reset() {
	*x = PlayResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayResponse) ProtoMessage() {}

func (x *PlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayResponse.ProtoReflect.Descriptor instead.
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{3}
}

func (x *PlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlayResponse) GetPlaybackId() string {
	if x != nil {
		return x.PlaybackId
	}
	return ""
}

func (x *PlayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StopRequest halts playback
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Immediate     bool                   `protobuf:"varint,3,opt,name=immediate,proto3" json:"immediate,omitempty"` // If true, stop without fade
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *StopRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *StopRequest) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{5}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// FadeRequest initiates crossfade
type FadeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	NextSource    *SourceConfig          `protobuf:"bytes,3,opt,name=next_source,json=nextSource,proto3" json:"next_source,omitempty"`
	NextCuePoints *CuePoints             `protobuf:"bytes,4,opt,name=next_cue_points,json=nextCuePoints,proto3" json:"next_cue_points,omitempty"`
	FadeConfig    *FadeConfig            `protobuf:"bytes,5,opt,name=fade_config,json=fadeConfig,proto3" json:"fade_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FadeRequest) Reset() {
	*x = FadeRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FadeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FadeRequest) ProtoMessage() {}

func (x *FadeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FadeRequest.ProtoReflect.Descriptor instead.
func (*FadeRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{6}
}

func (x *FadeRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *FadeRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *FadeRequest) GetNextSource() *SourceConfig {
	if x != nil {
		return x.NextSource
	}
	return nil
}

func (x *FadeRequest) GetNextCuePoints() *CuePoints {
	if x != nil {
		return x.NextCuePoints
	}
	return nil
}

func (x *FadeRequest) GetFadeConfig() *FadeConfig {
	if x != nil {
		return x.FadeConfig
	}
	return nil
}

type FadeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FadeId              string                 `protobuf:"bytes,2,opt,name=fade_id,json=fadeId,proto3" json:"fade_id,omitempty"`
	EstimatedDurationMs int64                  `protobuf:"varint,3,opt,name=estimated_duration_ms,json=estimatedDurationMs,proto3" json:"estimated_duration_ms,omitempty"`
	Error               string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FadeResponse) Reset() {
	*x = FadeResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FadeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FadeResponse) ProtoMessage() {}

func (x *FadeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FadeResponse.ProtoReflect.Descriptor instead.
func (*FadeResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{7}
}

func (x *FadeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FadeResponse) GetFadeId() string {
	if x != nil {
		return x.FadeId
	}
	return ""
}

func (x *FadeResponse) GetEstimatedDurationMs() int64 {
	if x != nil {
		return x.EstimatedDurationMs
	}
	return 0
}

func (x *FadeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// InsertEmergencyRequest for emergency broadcasts
type InsertEmergencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Source        *SourceConfig          `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertEmergencyRequest) Reset() {
	*x = InsertEmergencyRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertEmergencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertEmergencyRequest) ProtoMessage() {}

func (x *InsertEmergencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertEmergencyRequest.ProtoReflect.Descriptor instead.
func (*InsertEmergencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{8}
}

func (x *InsertEmergencyRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *InsertEmergencyRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *InsertEmergencyRequest) GetSource() *SourceConfig {
	if x != nil {
		return x.Source
	}
	return nil
}

type InsertEmergencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EmergencyId   string                 `protobuf:"bytes,2,opt,name=emergency_id,json=emergencyId,proto3" json:"emergency_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertEmergencyResponse) Reset() {
	*x = InsertEmergencyResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertEmergencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertEmergencyResponse) ProtoMessage() {}

func (x *InsertEmergencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertEmergencyResponse.ProtoReflect.Descriptor instead.
func (*InsertEmergencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{9}
}

func (x *InsertEmergencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertEmergencyResponse) GetEmergencyId() string {
	if x != nil {
		return x.EmergencyId
	}
	return ""
}

func (x *InsertEmergencyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RouteLiveRequest routes live input
type RouteLiveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StationId      string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId        string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                    // Live session ID
	InputType      LiveInputType          `protobuf:"varint,4,opt,name=input_type,json=inputType,proto3,enum=mediaengine.v1.LiveInputType" json:"input_type,omitempty"` // Type of live input
	InputUrl       string                 `protobuf:"bytes,5,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`                                       // Input URL (for HTTP/Icecast/SRT)
	Port           int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`                                                              // Port (for RTP/UDP)
	DspGraphHandle string                 `protobuf:"bytes,7,opt,name=dsp_graph_handle,json=dspGraphHandle,proto3" json:"dsp_graph_handle,omitempty"`                   // DSP graph to apply
	FadeInMs       int32                  `protobuf:"varint,8,opt,name=fade_in_ms,json=fadeInMs,proto3" json:"fade_in_ms,omitempty"`                                    // Fade in duration
	Input          *LiveInputConfig       `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`                                                             // Legacy field (deprecated)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteLiveRequest) Reset() {
	*x = RouteLiveRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLiveRequest) ProtoMessage() {}

func (x *RouteLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLiveRequest.ProtoReflect.Descriptor instead.
func (*RouteLiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{10}
}

func (x *RouteLiveRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *RouteLiveRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *RouteLiveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouteLiveRequest) GetInputType() LiveInputType {
	if x != nil {
		return x.InputType
	}
	return LiveInputType_LIVE_INPUT_TYPE_UNSPECIFIED
}

func (x *RouteLiveRequest) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *RouteLiveRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RouteLiveRequest) GetDspGraphHandle() string {
	if x != nil {
		return x.DspGraphHandle
	}
	return ""
}

func (x *RouteLiveRequest) GetFadeInMs() int32 {
	if x != nil {
		return x.FadeInMs
	}
	return 0
}

func (x *RouteLiveRequest) GetInput() *LiveInputConfig {
	if x != nil {
		return x.Input
	}
	return nil
}

type RouteLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Live session ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // Status message
	LiveId        string                 `protobuf:"bytes,4,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`          // Legacy field (deprecated)
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                          // Legacy field (deprecated)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteLiveResponse) Reset() {
	*x = RouteLiveResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLiveResponse) ProtoMessage() {}

func (x *RouteLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLiveResponse.ProtoReflect.Descriptor instead.
func (*RouteLiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{11}
}

func (x *RouteLiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteLiveResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouteLiveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RouteLiveResponse) GetLiveId() string {
	if x != nil {
		return x.LiveId
	}
	return ""
}

func (x *RouteLiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TelemetryRequest for streaming telemetry
type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	IntervalMs    int32                  `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Update interval in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{12}
}

func (x *TelemetryRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *TelemetryRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *TelemetryRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// TelemetryData contains real-time audio metrics
type TelemetryData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StationId string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId   string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Audio levels
	AudioLevelL float32 `protobuf:"fixed32,4,opt,name=audio_level_l,json=audioLevelL,proto3" json:"audio_level_l,omitempty"` // Left channel RMS (-60 to 0 dBFS)
	AudioLevelR float32 `protobuf:"fixed32,5,opt,name=audio_level_r,json=audioLevelR,proto3" json:"audio_level_r,omitempty"` // Right channel RMS
	PeakLevelL  float32 `protobuf:"fixed32,6,opt,name=peak_level_l,json=peakLevelL,proto3" json:"peak_level_l,omitempty"`    // Left channel peak
	PeakLevelR  float32 `protobuf:"fixed32,7,opt,name=peak_level_r,json=peakLevelR,proto3" json:"peak_level_r,omitempty"`    // Right channel peak
	// Loudness
	LoudnessLufs  float32 `protobuf:"fixed32,8,opt,name=loudness_lufs,json=loudnessLufs,proto3" json:"loudness_lufs,omitempty"`       // Integrated loudness (LUFS)
	MomentaryLufs float32 `protobuf:"fixed32,9,opt,name=momentary_lufs,json=momentaryLufs,proto3" json:"momentary_lufs,omitempty"`    // Momentary loudness
	ShortTermLufs float32 `protobuf:"fixed32,10,opt,name=short_term_lufs,json=shortTermLufs,proto3" json:"short_term_lufs,omitempty"` // Short-term loudness
	// Buffer state
	BufferDepthMs     int64 `protobuf:"varint,11,opt,name=buffer_depth_ms,json=bufferDepthMs,proto3" json:"buffer_depth_ms,omitempty"`
	BufferFillPercent int32 `protobuf:"varint,12,opt,name=buffer_fill_percent,json=bufferFillPercent,proto3" json:"buffer_fill_percent,omitempty"`
	UnderrunCount     int64 `protobuf:"varint,13,opt,name=underrun_count,json=underrunCount,proto3" json:"underrun_count,omitempty"`
	// Playback state
	State         PlaybackState `protobuf:"varint,14,opt,name=state,proto3,enum=mediaengine.v1.PlaybackState" json:"state,omitempty"`
	PositionMs    int64         `protobuf:"varint,15,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"` // Current playback position
	DurationMs    int64         `protobuf:"varint,16,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Total duration (if known)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{13}
}

func (x *TelemetryData) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *TelemetryData) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

func (x *TelemetryData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryData) GetAudioLevelL() float32 {
	if x != nil {
		return x.AudioLevelL
	}
	return 0
}

func (x *TelemetryData) GetAudioLevelR() float32 {
	if x != nil {
		return x.AudioLevelR
	}
	return 0
}

func (x *TelemetryData) GetPeakLevelL() float32 {
	if x != nil {
		return x.PeakLevelL
	}
	return 0
}

func (x *TelemetryData) GetPeakLevelR() float32 {
	if x != nil {
		return x.PeakLevelR
	}
	return 0
}

func (x *TelemetryData) GetLoudnessLufs() float32 {
	if x != nil {
		return x.LoudnessLufs
	}
	return 0
}

func (x *TelemetryData) GetMomentaryLufs() float32 {
	if x != nil {
		return x.MomentaryLufs
	}
	return 0
}

func (x *TelemetryData) GetShortTermLufs() float32 {
	if x != nil {
		return x.ShortTermLufs
	}
	return 0
}

func (x *TelemetryData) GetBufferDepthMs() int64 {
	if x != nil {
		return x.BufferDepthMs
	}
	return 0
}

func (x *TelemetryData) GetBufferFillPercent() int32 {
	if x != nil {
		return x.BufferFillPercent
	}
	return 0
}

func (x *TelemetryData) GetUnderrunCount() int64 {
	if x != nil {
		return x.UnderrunCount
	}
	return 0
}

func (x *TelemetryData) GetState() PlaybackState {
	if x != nil {
		return x.State
	}
	return PlaybackState_PLAYBACK_STATE_UNSPECIFIED
}

func (x *TelemetryData) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *TelemetryData) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// StatusRequest queries engine status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     string                 `protobuf:"bytes,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	MountId       string                 `protobuf:"bytes,2,opt,name=mount_id,json=mountId,proto3" json:"mount_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{14}
}

func (x *StatusRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *StatusRequest) GetMountId() string {
	if x != nil {
		return x.MountId
	}
	return ""
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Running         bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	State           PlaybackState          `protobuf:"varint,2,opt,name=state,proto3,enum=mediaengine.v1.PlaybackState" json:"state,omitempty"`
	CurrentSourceId string                 `protobuf:"bytes,3,opt,name=current_source_id,json=currentSourceId,proto3" json:"current_source_id,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	GraphHandle     string                 `protobuf:"bytes,5,opt,name=graph_handle,json=graphHandle,proto3" json:"graph_handle,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{15}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetState() PlaybackState {
	if x != nil {
		return x.State
	}
	return PlaybackState_PLAYBACK_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetCurrentSourceId() string {
	if x != nil {
		return x.CurrentSourceId
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetGraphHandle() string {
	if x != nil {
		return x.GraphHandle
	}
	return ""
}

func (x *StatusResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// SourceConfig describes an audio source
type SourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SourceType             `protobuf:"varint,1,opt,name=type,proto3,enum=mediaengine.v1.SourceType" json:"type,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // Media ID, webstream URL, etc.
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`                         // File path for media sources
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{16}
}

func (x *SourceConfig) GetType() SourceType {
	if x != nil {
		return x.Type
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *SourceConfig) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SourceConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SourceConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CuePoints for seamless mixing
type CuePoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntroEnd      float32                `protobuf:"fixed32,1,opt,name=intro_end,json=introEnd,proto3" json:"intro_end,omitempty"` // End of intro in seconds
	OutroIn       float32                `protobuf:"fixed32,2,opt,name=outro_in,json=outroIn,proto3" json:"outro_in,omitempty"`    // Start of outro in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CuePoints) Reset() {
	*x = CuePoints{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CuePoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuePoints) ProtoMessage() {}

func (x *CuePoints) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CuePoints.ProtoReflect.Descriptor instead.
func (*CuePoints) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{17}
}

func (x *CuePoints) GetIntroEnd() float32 {
	if x != nil {
		return x.IntroEnd
	}
	return 0
}

func (x *CuePoints) GetOutroIn() float32 {
	if x != nil {
		return x.OutroIn
	}
	return 0
}

// FadeConfig for crossfades
type FadeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FadeInMs      int32                  `protobuf:"varint,1,opt,name=fade_in_ms,json=fadeInMs,proto3" json:"fade_in_ms,omitempty"`
	FadeOutMs     int32                  `protobuf:"varint,2,opt,name=fade_out_ms,json=fadeOutMs,proto3" json:"fade_out_ms,omitempty"`
	Curve         FadeCurve              `protobuf:"varint,3,opt,name=curve,proto3,enum=mediaengine.v1.FadeCurve" json:"curve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FadeConfig) Reset() {
	*x = FadeConfig{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FadeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FadeConfig) ProtoMessage() {}

func (x *FadeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FadeConfig.ProtoReflect.Descriptor instead.
func (*FadeConfig) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{18}
}

func (x *FadeConfig) GetFadeInMs() int32 {
	if x != nil {
		return x.FadeInMs
	}
	return 0
}

func (x *FadeConfig) GetFadeOutMs() int32 {
	if x != nil {
		return x.FadeOutMs
	}
	return 0
}

func (x *FadeConfig) GetCurve() FadeCurve {
	if x != nil {
		return x.Curve
	}
	return FadeCurve_FADE_CURVE_UNSPECIFIED
}

// LiveInputConfig for live streaming
type LiveInputConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputUrl        string                 `protobuf:"bytes,1,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`                       // Harbor/HTTP input URL
	AuthToken       string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`                    // Authentication token
	BufferMs        int32                  `protobuf:"varint,3,opt,name=buffer_ms,json=bufferMs,proto3" json:"buffer_ms,omitempty"`                      // Input buffer size
	ApplyProcessing bool                   `protobuf:"varint,4,opt,name=apply_processing,json=applyProcessing,proto3" json:"apply_processing,omitempty"` // Apply DSP graph to live input
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LiveInputConfig) Reset() {
	*x = LiveInputConfig{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveInputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveInputConfig) ProtoMessage() {}

func (x *LiveInputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveInputConfig.ProtoReflect.Descriptor instead.
func (*LiveInputConfig) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{19}
}

func (x *LiveInputConfig) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *LiveInputConfig) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *LiveInputConfig) GetBufferMs() int32 {
	if x != nil {
		return x.BufferMs
	}
	return 0
}

func (x *LiveInputConfig) GetApplyProcessing() bool {
	if x != nil {
		return x.ApplyProcessing
	}
	return false
}

// DSPGraph defines audio processing chain
type DSPGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*DSPNode             `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Connections   []*DSPConnection       `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DSPGraph) Reset() {
	*x = DSPGraph{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSPGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSPGraph) ProtoMessage() {}

func (x *DSPGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSPGraph.ProtoReflect.Descriptor instead.
func (*DSPGraph) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{20}
}

func (x *DSPGraph) GetNodes() []*DSPNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DSPGraph) GetConnections() []*DSPConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

// DSPNode represents a processing element
type DSPNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=mediaengine.v1.NodeType" json:"type,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DSPNode) Reset() {
	*x = DSPNode{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSPNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSPNode) ProtoMessage() {}

func (x *DSPNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSPNode.ProtoReflect.Descriptor instead.
func (*DSPNode) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{21}
}

func (x *DSPNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DSPNode) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *DSPNode) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// DSPConnection links nodes
type DSPConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	FromPad       int32                  `protobuf:"varint,3,opt,name=from_pad,json=fromPad,proto3" json:"from_pad,omitempty"`
	ToPad         int32                  `protobuf:"varint,4,opt,name=to_pad,json=toPad,proto3" json:"to_pad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DSPConnection) Reset() {
	*x = DSPConnection{}
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DSPConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DSPConnection) ProtoMessage() {}

func (x *DSPConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mediaengine_v1_mediaengine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DSPConnection.ProtoReflect.Descriptor instead.
func (*DSPConnection) Descriptor() ([]byte, []int) {
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP(), []int{22}
}

func (x *DSPConnection) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *DSPConnection) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *DSPConnection) GetFromPad() int32 {
	if x != nil {
		return x.FromPad
	}
	return 0
}

func (x *DSPConnection) GetToPad() int32 {
	if x != nil {
		return x.ToPad
	}
	return 0
}

var File_proto_mediaengine_v1_mediaengine_proto protoreflect.FileDescriptor

const file_proto_mediaengine_v1_mediaengine_proto_rawDesc = "" +
	"\n" +
	"&proto/mediaengine/v1/mediaengine.proto\x12\x0emediaengine.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\x10LoadGraphRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x12.\n" +
	"\x05graph\x18\x03 \x01(\v2\x18.mediaengine.v1.DSPGraphR\x05graph\"f\n" +
	"\x11LoadGraphResponse\x12!\n" +
	"\fgraph_handle\x18\x01 \x01(\tR\vgraphHandle\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x83\x02\n" +
	"\vPlayRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x124\n" +
	"\x06source\x18\x03 \x01(\v2\x1c.mediaengine.v1.SourceConfigR\x06source\x128\n" +
	"\n" +
	"cue_points\x18\x04 \x01(\v2\x19.mediaengine.v1.CuePointsR\tcuePoints\x12.\n" +
	"\x04fade\x18\x05 \x01(\v2\x1a.mediaengine.v1.FadeConfigR\x04fade\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\"_\n" +
	"\fPlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vplayback_id\x18\x02 \x01(\tR\n" +
	"playbackId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"e\n" +
	"\vStopRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x12\x1c\n" +
	"\timmediate\x18\x03 \x01(\bR\timmediate\">\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x86\x02\n" +
	"\vFadeRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x12=\n" +
	"\vnext_source\x18\x03 \x01(\v2\x1c.mediaengine.v1.SourceConfigR\n" +
	"nextSource\x12A\n" +
	"\x0fnext_cue_points\x18\x04 \x01(\v2\x19.mediaengine.v1.CuePointsR\rnextCuePoints\x12;\n" +
	"\vfade_config\x18\x05 \x01(\v2\x1a.mediaengine.v1.FadeConfigR\n" +
	"fadeConfig\"\x8b\x01\n" +
	"\fFadeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\afade_id\x18\x02 \x01(\tR\x06fadeId\x122\n" +
	"\x15estimated_duration_ms\x18\x03 \x01(\x03R\x13estimatedDurationMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x88\x01\n" +
	"\x16InsertEmergencyRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x124\n" +
	"\x06source\x18\x03 \x01(\v2\x1c.mediaengine.v1.SourceConfigR\x06source\"l\n" +
	"\x17InsertEmergencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\femergency_id\x18\x02 \x01(\tR\vemergencyId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd9\x02\n" +
	"\x10RouteLiveRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12<\n" +
	"\n" +
	"input_type\x18\x04 \x01(\x0e2\x1d.mediaengine.v1.LiveInputTypeR\tinputType\x12\x1b\n" +
	"\tinput_url\x18\x05 \x01(\tR\binputUrl\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12(\n" +
	"\x10dsp_graph_handle\x18\a \x01(\tR\x0edspGraphHandle\x12\x1c\n" +
	"\n" +
	"fade_in_ms\x18\b \x01(\x05R\bfadeInMs\x125\n" +
	"\x05input\x18\t \x01(\v2\x1f.mediaengine.v1.LiveInputConfigR\x05input\"\x95\x01\n" +
	"\x11RouteLiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\alive_id\x18\x04 \x01(\tR\x06liveId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"m\n" +
	"\x10TelemetryRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x05R\n" +
	"intervalMs\"\xf9\x04\n" +
	"\rTelemetryData\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\"\n" +
	"\raudio_level_l\x18\x04 \x01(\x02R\vaudioLevelL\x12\"\n" +
	"\raudio_level_r\x18\x05 \x01(\x02R\vaudioLevelR\x12 \n" +
	"\fpeak_level_l\x18\x06 \x01(\x02R\n" +
	"peakLevelL\x12 \n" +
	"\fpeak_level_r\x18\a \x01(\x02R\n" +
	"peakLevelR\x12#\n" +
	"\rloudness_lufs\x18\b \x01(\x02R\floudnessLufs\x12%\n" +
	"\x0emomentary_lufs\x18\t \x01(\x02R\rmomentaryLufs\x12&\n" +
	"\x0fshort_term_lufs\x18\n" +
	" \x01(\x02R\rshortTermLufs\x12&\n" +
	"\x0fbuffer_depth_ms\x18\v \x01(\x03R\rbufferDepthMs\x12.\n" +
	"\x13buffer_fill_percent\x18\f \x01(\x05R\x11bufferFillPercent\x12%\n" +
	"\x0eunderrun_count\x18\r \x01(\x03R\runderrunCount\x123\n" +
	"\x05state\x18\x0e \x01(\x0e2\x1d.mediaengine.v1.PlaybackStateR\x05state\x12\x1f\n" +
	"\vposition_ms\x18\x0f \x01(\x03R\n" +
	"positionMs\x12\x1f\n" +
	"\vduration_ms\x18\x10 \x01(\x03R\n" +
	"durationMs\"I\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\tR\tstationId\x12\x19\n" +
	"\bmount_id\x18\x02 \x01(\tR\amountId\"\xdc\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.mediaengine.v1.PlaybackStateR\x05state\x12*\n" +
	"\x11current_source_id\x18\x03 \x01(\tR\x0fcurrentSourceId\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fgraph_handle\x18\x05 \x01(\tR\vgraphHandle\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.mediaengine.v1.StatusResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\fSourceConfig\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.mediaengine.v1.SourceTypeR\x04type\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.mediaengine.v1.SourceConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\tCuePoints\x12\x1b\n" +
	"\tintro_end\x18\x01 \x01(\x02R\bintroEnd\x12\x19\n" +
	"\boutro_in\x18\x02 \x01(\x02R\aoutroIn\"{\n" +
	"\n" +
	"FadeConfig\x12\x1c\n" +
	"\n" +
	"fade_in_ms\x18\x01 \x01(\x05R\bfadeInMs\x12\x1e\n" +
	"\vfade_out_ms\x18\x02 \x01(\x05R\tfadeOutMs\x12/\n" +
	"\x05curve\x18\x03 \x01(\x0e2\x19.mediaengine.v1.FadeCurveR\x05curve\"\x95\x01\n" +
	"\x0fLiveInputConfig\x12\x1b\n" +
	"\tinput_url\x18\x01 \x01(\tR\binputUrl\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1b\n" +
	"\tbuffer_ms\x18\x03 \x01(\x05R\bbufferMs\x12)\n" +
	"\x10apply_processing\x18\x04 \x01(\bR\x0fapplyProcessing\"z\n" +
	"\bDSPGraph\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.mediaengine.v1.DSPNodeR\x05nodes\x12?\n" +
	"\vconnections\x18\x02 \x03(\v2\x1d.mediaengine.v1.DSPConnectionR\vconnections\"\xbf\x01\n" +
	"\aDSPNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.mediaengine.v1.NodeTypeR\x04type\x12;\n" +
	"\x06params\x18\x03 \x03(\v2#.mediaengine.v1.DSPNode.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\rDSPConnection\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\x12\x19\n" +
	"\bfrom_pad\x18\x03 \x01(\x05R\afromPad\x12\x15\n" +
	"\x06to_pad\x18\x04 \x01(\x05R\x05toPad*\xa6\x01\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SOURCE_TYPE_MEDIA\x10\x01\x12\x19\n" +
	"\x15SOURCE_TYPE_WEBSTREAM\x10\x02\x12\x14\n" +
	"\x10SOURCE_TYPE_LIVE\x10\x03\x12\x18\n" +
	"\x14SOURCE_TYPE_FALLBACK\x10\x04\x12\x19\n" +
	"\x15SOURCE_TYPE_EMERGENCY\x10\x05*\x9b\x01\n" +
	"\rLiveInputType\x12\x1f\n" +
	"\x1bLIVE_INPUT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LIVE_INPUT_TYPE_ICECAST\x10\x01\x12\x17\n" +
	"\x13LIVE_INPUT_TYPE_RTP\x10\x02\x12\x17\n" +
	"\x13LIVE_INPUT_TYPE_SRT\x10\x03\x12\x1a\n" +
	"\x16LIVE_INPUT_TYPE_WEBRTC\x10\x04*\xd0\x01\n" +
	"\rPlaybackState\x12\x1e\n" +
	"\x1aPLAYBACK_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PLAYBACK_STATE_IDLE\x10\x01\x12\x1a\n" +
	"\x16PLAYBACK_STATE_LOADING\x10\x02\x12\x1a\n" +
	"\x16PLAYBACK_STATE_PLAYING\x10\x03\x12\x19\n" +
	"\x15PLAYBACK_STATE_FADING\x10\x04\x12\x19\n" +
	"\x15PLAYBACK_STATE_PAUSED\x10\x05\x12\x18\n" +
	"\x14PLAYBACK_STATE_ERROR\x10\x06*\x8d\x01\n" +
	"\tFadeCurve\x12\x1a\n" +
	"\x16FADE_CURVE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FADE_CURVE_LINEAR\x10\x01\x12\x1a\n" +
	"\x16FADE_CURVE_LOGARITHMIC\x10\x02\x12\x1a\n" +
	"\x16FADE_CURVE_EXPONENTIAL\x10\x03\x12\x15\n" +
	"\x11FADE_CURVE_SCURVE\x10\x04*\xc5\x02\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNODE_TYPE_INPUT\x10\x01\x12\x14\n" +
	"\x10NODE_TYPE_OUTPUT\x10\x02\x12 \n" +
	"\x1cNODE_TYPE_LOUDNESS_NORMALIZE\x10\x03\x12\x11\n" +
	"\rNODE_TYPE_AGC\x10\x04\x12\x18\n" +
	"\x14NODE_TYPE_COMPRESSOR\x10\x05\x12\x15\n" +
	"\x11NODE_TYPE_LIMITER\x10\x06\x12\x17\n" +
	"\x13NODE_TYPE_EQUALIZER\x10\a\x12\x12\n" +
	"\x0eNODE_TYPE_GATE\x10\b\x12\x1e\n" +
	"\x1aNODE_TYPE_SILENCE_DETECTOR\x10\t\x12\x19\n" +
	"\x15NODE_TYPE_LEVEL_METER\x10\n" +
	"\x12\x11\n" +
	"\rNODE_TYPE_MIX\x10\v\x12\x12\n" +
	"\x0eNODE_TYPE_DUCK\x10\f2\x80\x05\n" +
	"\vMediaEngine\x12P\n" +
	"\tLoadGraph\x12 .mediaengine.v1.LoadGraphRequest\x1a!.mediaengine.v1.LoadGraphResponse\x12A\n" +
	"\x04Play\x12\x1b.mediaengine.v1.PlayRequest\x1a\x1c.mediaengine.v1.PlayResponse\x12A\n" +
	"\x04Stop\x12\x1b.mediaengine.v1.StopRequest\x1a\x1c.mediaengine.v1.StopResponse\x12A\n" +
	"\x04Fade\x12\x1b.mediaengine.v1.FadeRequest\x1a\x1c.mediaengine.v1.FadeResponse\x12b\n" +
	"\x0fInsertEmergency\x12&.mediaengine.v1.InsertEmergencyRequest\x1a'.mediaengine.v1.InsertEmergencyResponse\x12P\n" +
	"\tRouteLive\x12 .mediaengine.v1.RouteLiveRequest\x1a!.mediaengine.v1.RouteLiveResponse\x12T\n" +
	"\x0fStreamTelemetry\x12 .mediaengine.v1.TelemetryRequest\x1a\x1d.mediaengine.v1.TelemetryData0\x01\x12J\n" +
	"\tGetStatus\x12\x1d.mediaengine.v1.StatusRequest\x1a\x1e.mediaengine.v1.StatusResponseBKZIgithub.com/friendsincode/grimnir_radio/proto/mediaengine/v1;mediaenginev1b\x06proto3"

var (
	file_proto_mediaengine_v1_mediaengine_proto_rawDescOnce sync.Once
	file_proto_mediaengine_v1_mediaengine_proto_rawDescData []byte
)

func file_proto_mediaengine_v1_mediaengine_proto_rawDescGZIP() []byte {
	file_proto_mediaengine_v1_mediaengine_proto_rawDescOnce.Do(func() {
		file_proto_mediaengine_v1_mediaengine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mediaengine_v1_mediaengine_proto_rawDesc), len(file_proto_mediaengine_v1_mediaengine_proto_rawDesc)))
	})
	return file_proto_mediaengine_v1_mediaengine_proto_rawDescData
}

var file_proto_mediaengine_v1_mediaengine_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_mediaengine_v1_mediaengine_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_mediaengine_v1_mediaengine_proto_goTypes = []any{
	(SourceType)(0),                 // 0: mediaengine.v1.SourceType
	(LiveInputType)(0),              // 1: mediaengine.v1.LiveInputType
	(PlaybackState)(0),              // 2: mediaengine.v1.PlaybackState
	(FadeCurve)(0),                  // 3: mediaengine.v1.FadeCurve
	(NodeType)(0),                   // 4: mediaengine.v1.NodeType
	(*LoadGraphRequest)(nil),        // 5: mediaengine.v1.LoadGraphRequest
	(*LoadGraphResponse)(nil),       // 6: mediaengine.v1.LoadGraphResponse
	(*PlayRequest)(nil),             // 7: mediaengine.v1.PlayRequest
	(*PlayResponse)(nil),            // 8: mediaengine.v1.PlayResponse
	(*StopRequest)(nil),             // 9: mediaengine.v1.StopRequest
	(*StopResponse)(nil),            // 10: mediaengine.v1.StopResponse
	(*FadeRequest)(nil),             // 11: mediaengine.v1.FadeRequest
	(*FadeResponse)(nil),            // 12: mediaengine.v1.FadeResponse
	(*InsertEmergencyRequest)(nil),  // 13: mediaengine.v1.InsertEmergencyRequest
	(*InsertEmergencyResponse)(nil), // 14: mediaengine.v1.InsertEmergencyResponse
	(*RouteLiveRequest)(nil),        // 15: mediaengine.v1.RouteLiveRequest
	(*RouteLiveResponse)(nil),       // 16: mediaengine.v1.RouteLiveResponse
	(*TelemetryRequest)(nil),        // 17: mediaengine.v1.TelemetryRequest
	(*TelemetryData)(nil),           // 18: mediaengine.v1.TelemetryData
	(*StatusRequest)(nil),           // 19: mediaengine.v1.StatusRequest
	(*StatusResponse)(nil),          // 20: mediaengine.v1.StatusResponse
	(*SourceConfig)(nil),            // 21: mediaengine.v1.SourceConfig
	(*CuePoints)(nil),               // 22: mediaengine.v1.CuePoints
	(*FadeConfig)(nil),              // 23: mediaengine.v1.FadeConfig
	(*LiveInputConfig)(nil),         // 24: mediaengine.v1.LiveInputConfig
	(*DSPGraph)(nil),                // 25: mediaengine.v1.DSPGraph
	(*DSPNode)(nil),                 // 26: mediaengine.v1.DSPNode
	(*DSPConnection)(nil),           // 27: mediaengine.v1.DSPConnection
	nil,                             // 28: mediaengine.v1.StatusResponse.MetadataEntry
	nil,                             // 29: mediaengine.v1.SourceConfig.MetadataEntry
	nil,                             // 30: mediaengine.v1.DSPNode.ParamsEntry
	(*timestamppb.Timestamp)(nil),   // 31: google.protobuf.Timestamp
}
var file_proto_mediaengine_v1_mediaengine_proto_depIdxs = []int32{
	25, // 0: mediaengine.v1.LoadGraphRequest.graph:type_name -> mediaengine.v1.DSPGraph
	21, // 1: mediaengine.v1.PlayRequest.source:type_name -> mediaengine.v1.SourceConfig
	22, // 2: mediaengine.v1.PlayRequest.cue_points:type_name -> mediaengine.v1.CuePoints
	23, // 3: mediaengine.v1.PlayRequest.fade:type_name -> mediaengine.v1.FadeConfig
	21, // 4: mediaengine.v1.FadeRequest.next_source:type_name -> mediaengine.v1.SourceConfig
	22, // 5: mediaengine.v1.FadeRequest.next_cue_points:type_name -> mediaengine.v1.CuePoints
	23, // 6: mediaengine.v1.FadeRequest.fade_config:type_name -> mediaengine.v1.FadeConfig
	21, // 7: mediaengine.v1.InsertEmergencyRequest.source:type_name -> mediaengine.v1.SourceConfig
	1,  // 8: mediaengine.v1.RouteLiveRequest.input_type:type_name -> mediaengine.v1.LiveInputType
	24, // 9: mediaengine.v1.RouteLiveRequest.input:type_name -> mediaengine.v1.LiveInputConfig
	31, // 10: mediaengine.v1.TelemetryData.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 11: mediaengine.v1.TelemetryData.state:type_name -> mediaengine.v1.PlaybackState
	2,  // 12: mediaengine.v1.StatusResponse.state:type_name -> mediaengine.v1.PlaybackState
	28, // 13: mediaengine.v1.StatusResponse.metadata:type_name -> mediaengine.v1.StatusResponse.MetadataEntry
	0,  // 14: mediaengine.v1.SourceConfig.type:type_name -> mediaengine.v1.SourceType
	29, // 15: mediaengine.v1.SourceConfig.metadata:type_name -> mediaengine.v1.SourceConfig.MetadataEntry
	3,  // 16: mediaengine.v1.FadeConfig.curve:type_name -> mediaengine.v1.FadeCurve
	26, // 17: mediaengine.v1.DSPGraph.nodes:type_name -> mediaengine.v1.DSPNode
	27, // 18: mediaengine.v1.DSPGraph.connections:type_name -> mediaengine.v1.DSPConnection
	4,  // 19: mediaengine.v1.DSPNode.type:type_name -> mediaengine.v1.NodeType
	30, // 20: mediaengine.v1.DSPNode.params:type_name -> mediaengine.v1.DSPNode.ParamsEntry
	5,  // 21: mediaengine.v1.MediaEngine.LoadGraph:input_type -> mediaengine.v1.LoadGraphRequest
	7,  // 22: mediaengine.v1.MediaEngine.Play:input_type -> mediaengine.v1.PlayRequest
	9,  // 23: mediaengine.v1.MediaEngine.Stop:input_type -> mediaengine.v1.StopRequest
	11, // 24: mediaengine.v1.MediaEngine.Fade:input_type -> mediaengine.v1.FadeRequest
	13, // 25: mediaengine.v1.MediaEngine.InsertEmergency:input_type -> mediaengine.v1.InsertEmergencyRequest
	15, // 26: mediaengine.v1.MediaEngine.RouteLive:input_type -> mediaengine.v1.RouteLiveRequest
	17, // 27: mediaengine.v1.MediaEngine.StreamTelemetry:input_type -> mediaengine.v1.TelemetryRequest
	19, // 28: mediaengine.v1.MediaEngine.GetStatus:input_type -> mediaengine.v1.StatusRequest
	6,  // 29: mediaengine.v1.MediaEngine.LoadGraph:output_type -> mediaengine.v1.LoadGraphResponse
	8,  // 30: mediaengine.v1.MediaEngine.Play:output_type -> mediaengine.v1.PlayResponse
	10, // 31: mediaengine.v1.MediaEngine.Stop:output_type -> mediaengine.v1.StopResponse
	12, // 32: mediaengine.v1.MediaEngine.Fade:output_type -> mediaengine.v1.FadeResponse
	14, // 33: mediaengine.v1.MediaEngine.InsertEmergency:output_type -> mediaengine.v1.InsertEmergencyResponse
	16, // 34: mediaengine.v1.MediaEngine.RouteLive:output_type -> mediaengine.v1.RouteLiveResponse
	18, // 35: mediaengine.v1.MediaEngine.StreamTelemetry:output_type -> mediaengine.v1.TelemetryData
	20, // 36: mediaengine.v1.MediaEngine.GetStatus:output_type -> mediaengine.v1.StatusResponse
	29, // [29:37] is the sub-list for method output_type
	21, // [21:29] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_proto_mediaengine_v1_mediaengine_proto_init() }
func file_proto_mediaengine_v1_mediaengine_proto_init() {
	if File_proto_mediaengine_v1_mediaengine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mediaengine_v1_mediaengine_proto_rawDesc), len(file_proto_mediaengine_v1_mediaengine_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mediaengine_v1_mediaengine_proto_goTypes,
		DependencyIndexes: file_proto_mediaengine_v1_mediaengine_proto_depIdxs,
		EnumInfos:         file_proto_mediaengine_v1_mediaengine_proto_enumTypes,
		MessageInfos:      file_proto_mediaengine_v1_mediaengine_proto_msgTypes,
	}.Build()
	File_proto_mediaengine_v1_mediaengine_proto = out.File
	file_proto_mediaengine_v1_mediaengine_proto_goTypes = nil
	file_proto_mediaengine_v1_mediaengine_proto_depIdxs = nil
}
