/*
Copyright (C) 2026 Friends Incode

SPDX-License-Identifier: AGPL-3.0-or-later
*/


// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/mediaengine/v1/mediaengine.proto

package mediaenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaEngine_LoadGraph_FullMethodName       = "/mediaengine.v1.MediaEngine/LoadGraph"
	MediaEngine_Play_FullMethodName            = "/mediaengine.v1.MediaEngine/Play"
	MediaEngine_Stop_FullMethodName            = "/mediaengine.v1.MediaEngine/Stop"
	MediaEngine_Fade_FullMethodName            = "/mediaengine.v1.MediaEngine/Fade"
	MediaEngine_InsertEmergency_FullMethodName = "/mediaengine.v1.MediaEngine/InsertEmergency"
	MediaEngine_RouteLive_FullMethodName       = "/mediaengine.v1.MediaEngine/RouteLive"
	MediaEngine_StreamTelemetry_FullMethodName = "/mediaengine.v1.MediaEngine/StreamTelemetry"
	MediaEngine_GetStatus_FullMethodName       = "/mediaengine.v1.MediaEngine/GetStatus"
)

// MediaEngineClient is the client API for MediaEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaEngine service controls audio playback, DSP processing, and output encoding.
type MediaEngineClient interface {
	// LoadGraph loads a DSP processing graph configuration
	LoadGraph(ctx context.Context, in *LoadGraphRequest, opts ...grpc.CallOption) (*LoadGraphResponse, error)
	// Play starts playback of a media source
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayResponse, error)
	// Stop halts playback
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Fade initiates a crossfade between sources
	Fade(ctx context.Context, in *FadeRequest, opts ...grpc.CallOption) (*FadeResponse, error)
	// InsertEmergency immediately plays emergency content
	InsertEmergency(ctx context.Context, in *InsertEmergencyRequest, opts ...grpc.CallOption) (*InsertEmergencyResponse, error)
	// RouteLive routes a live input stream
	RouteLive(ctx context.Context, in *RouteLiveRequest, opts ...grpc.CallOption) (*RouteLiveResponse, error)
	// StreamTelemetry streams real-time audio telemetry
	StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryData], error)
	// GetStatus returns current engine status
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type mediaEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaEngineClient(cc grpc.ClientConnInterface) MediaEngineClient {
	return &mediaEngineClient{cc}
}

func (c *mediaEngineClient) LoadGraph(ctx context.Context, in *LoadGraphRequest, opts ...grpc.CallOption) (*LoadGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadGraphResponse)
	err := c.cc.Invoke(ctx, MediaEngine_LoadGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayResponse)
	err := c.cc.Invoke(ctx, MediaEngine_Play_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, MediaEngine_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) Fade(ctx context.Context, in *FadeRequest, opts ...grpc.CallOption) (*FadeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FadeResponse)
	err := c.cc.Invoke(ctx, MediaEngine_Fade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) InsertEmergency(ctx context.Context, in *InsertEmergencyRequest, opts ...grpc.CallOption) (*InsertEmergencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertEmergencyResponse)
	err := c.cc.Invoke(ctx, MediaEngine_InsertEmergency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) RouteLive(ctx context.Context, in *RouteLiveRequest, opts ...grpc.CallOption) (*RouteLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteLiveResponse)
	err := c.cc.Invoke(ctx, MediaEngine_RouteLive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaEngineClient) StreamTelemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetryData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaEngine_ServiceDesc.Streams[0], MediaEngine_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetryData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaEngine_StreamTelemetryClient = grpc.ServerStreamingClient[TelemetryData]

func (c *mediaEngineClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, MediaEngine_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaEngineServer is the server API for MediaEngine service.
// All implementations must embed UnimplementedMediaEngineServer
// for forward compatibility.
//
// MediaEngine service controls audio playback, DSP processing, and output encoding.
type MediaEngineServer interface {
	// LoadGraph loads a DSP processing graph configuration
	LoadGraph(context.Context, *LoadGraphRequest) (*LoadGraphResponse, error)
	// Play starts playback of a media source
	Play(context.Context, *PlayRequest) (*PlayResponse, error)
	// Stop halts playback
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	// Fade initiates a crossfade between sources
	Fade(context.Context, *FadeRequest) (*FadeResponse, error)
	// InsertEmergency immediately plays emergency content
	InsertEmergency(context.Context, *InsertEmergencyRequest) (*InsertEmergencyResponse, error)
	// RouteLive routes a live input stream
	RouteLive(context.Context, *RouteLiveRequest) (*RouteLiveResponse, error)
	// StreamTelemetry streams real-time audio telemetry
	StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryData]) error
	// GetStatus returns current engine status
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedMediaEngineServer()
}

// UnimplementedMediaEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaEngineServer struct{}

func (UnimplementedMediaEngineServer) LoadGraph(context.Context, *LoadGraphRequest) (*LoadGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadGraph not implemented")
}
func (UnimplementedMediaEngineServer) Play(context.Context, *PlayRequest) (*PlayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedMediaEngineServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedMediaEngineServer) Fade(context.Context, *FadeRequest) (*FadeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fade not implemented")
}
func (UnimplementedMediaEngineServer) InsertEmergency(context.Context, *InsertEmergencyRequest) (*InsertEmergencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertEmergency not implemented")
}
func (UnimplementedMediaEngineServer) RouteLive(context.Context, *RouteLiveRequest) (*RouteLiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteLive not implemented")
}
func (UnimplementedMediaEngineServer) StreamTelemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetryData]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedMediaEngineServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMediaEngineServer) mustEmbedUnimplementedMediaEngineServer() {}
func (UnimplementedMediaEngineServer) testEmbeddedByValue()                     {}

// UnsafeMediaEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaEngineServer will
// result in compilation errors.
type UnsafeMediaEngineServer interface {
	mustEmbedUnimplementedMediaEngineServer()
}

func RegisterMediaEngineServer(s grpc.ServiceRegistrar, srv MediaEngineServer) {
	// If the following call panics, it indicates UnimplementedMediaEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaEngine_ServiceDesc, srv)
}

func _MediaEngine_LoadGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).LoadGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_LoadGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).LoadGraph(ctx, req.(*LoadGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_Play_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).Play(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_Fade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FadeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).Fade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_Fade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).Fade(ctx, req.(*FadeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_InsertEmergency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertEmergencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).InsertEmergency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_InsertEmergency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).InsertEmergency(ctx, req.(*InsertEmergencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_RouteLive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).RouteLive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_RouteLive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).RouteLive(ctx, req.(*RouteLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaEngine_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaEngineServer).StreamTelemetry(m, &grpc.GenericServerStream[TelemetryRequest, TelemetryData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaEngine_StreamTelemetryServer = grpc.ServerStreamingServer[TelemetryData]

func _MediaEngine_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaEngineServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaEngine_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaEngineServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaEngine_ServiceDesc is the grpc.ServiceDesc for MediaEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mediaengine.v1.MediaEngine",
	HandlerType: (*MediaEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadGraph",
			Handler:    _MediaEngine_LoadGraph_Handler,
		},
		{
			MethodName: "Play",
			Handler:    _MediaEngine_Play_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _MediaEngine_Stop_Handler,
		},
		{
			MethodName: "Fade",
			Handler:    _MediaEngine_Fade_Handler,
		},
		{
			MethodName: "InsertEmergency",
			Handler:    _MediaEngine_InsertEmergency_Handler,
		},
		{
			MethodName: "RouteLive",
			Handler:    _MediaEngine_RouteLive_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MediaEngine_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _MediaEngine_StreamTelemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mediaengine/v1/mediaengine.proto",
}
