// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/edgeencoder/v1/edgeencoder.proto

package edgeencoderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_edgeencoder_v1_edgeencoder_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveInput   string                 `protobuf:"bytes,3,opt,name=active_input,json=activeInput,proto3" json:"active_input,omitempty"` // "A", "B", or "none"
	InputAHealthy bool                   `protobuf:"varint,4,opt,name=input_a_healthy,json=inputAHealthy,proto3" json:"input_a_healthy,omitempty"`
	InputBHealthy bool                   `protobuf:"varint,5,opt,name=input_b_healthy,json=inputBHealthy,proto3" json:"input_b_healthy,omitempty"`
	ListenerCount int64                  `protobuf:"varint,6,opt,name=listener_count,json=listenerCount,proto3" json:"listener_count,omitempty"`
	SwitchCount   int64                  `protobuf:"varint,7,opt,name=switch_count,json=switchCount,proto3" json:"switch_count,omitempty"`
	// Engine-divergence detection (issue #236). Phase 1 surfaces RTP-timestamp
	// divergence between the two engines; the audio-fingerprint variant is a
	// follow-up. The detector currently observes & reports; it does not pin or
	// force-switch.
	DivergenceDetected bool  `protobuf:"varint,8,opt,name=divergence_detected,json=divergenceDetected,proto3" json:"divergence_detected,omitempty"`
	DivergenceCount    int64 `protobuf:"varint,9,opt,name=divergence_count,json=divergenceCount,proto3" json:"divergence_count,omitempty"`
	// Seconds since the last divergence event, or -1 if none has occurred.
	LastDivergenceSecondsAgo int64 `protobuf:"varint,10,opt,name=last_divergence_seconds_ago,json=lastDivergenceSecondsAgo,proto3" json:"last_divergence_seconds_ago,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_edgeencoder_v1_edgeencoder_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetActiveInput() string {
	if x != nil {
		return x.ActiveInput
	}
	return ""
}

func (x *StatusResponse) GetInputAHealthy() bool {
	if x != nil {
		return x.InputAHealthy
	}
	return false
}

func (x *StatusResponse) GetInputBHealthy() bool {
	if x != nil {
		return x.InputBHealthy
	}
	return false
}

func (x *StatusResponse) GetListenerCount() int64 {
	if x != nil {
		return x.ListenerCount
	}
	return 0
}

func (x *StatusResponse) GetSwitchCount() int64 {
	if x != nil {
		return x.SwitchCount
	}
	return 0
}

func (x *StatusResponse) GetDivergenceDetected() bool {
	if x != nil {
		return x.DivergenceDetected
	}
	return false
}

func (x *StatusResponse) GetDivergenceCount() int64 {
	if x != nil {
		return x.DivergenceCount
	}
	return 0
}

func (x *StatusResponse) GetLastDivergenceSecondsAgo() int64 {
	if x != nil {
		return x.LastDivergenceSecondsAgo
	}
	return 0
}

var File_proto_edgeencoder_v1_edgeencoder_proto protoreflect.FileDescriptor

const file_proto_edgeencoder_v1_edgeencoder_proto_rawDesc = "" +
	"\n" +
	"&proto/edgeencoder/v1/edgeencoder.proto\x12\x0eedgeencoder.v1\"\x0f\n" +
	"\rStatusRequest\"\xa9\x03\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\factive_input\x18\x03 \x01(\tR\vactiveInput\x12&\n" +
	"\x0finput_a_healthy\x18\x04 \x01(\bR\rinputAHealthy\x12&\n" +
	"\x0finput_b_healthy\x18\x05 \x01(\bR\rinputBHealthy\x12%\n" +
	"\x0elistener_count\x18\x06 \x01(\x03R\rlistenerCount\x12!\n" +
	"\fswitch_count\x18\a \x01(\x03R\vswitchCount\x12/\n" +
	"\x13divergence_detected\x18\b \x01(\bR\x12divergenceDetected\x12)\n" +
	"\x10divergence_count\x18\t \x01(\x03R\x0fdivergenceCount\x12=\n" +
	"\x1blast_divergence_seconds_ago\x18\n" +
	" \x01(\x03R\x18lastDivergenceSecondsAgo2Y\n" +
	"\vEdgeEncoder\x12J\n" +
	"\tGetStatus\x12\x1d.edgeencoder.v1.StatusRequest\x1a\x1e.edgeencoder.v1.StatusResponseBKZIgithub.com/friendsincode/grimnir_radio/proto/edgeencoder/v1;edgeencoderv1b\x06proto3"

var (
	file_proto_edgeencoder_v1_edgeencoder_proto_rawDescOnce sync.Once
	file_proto_edgeencoder_v1_edgeencoder_proto_rawDescData []byte
)

func file_proto_edgeencoder_v1_edgeencoder_proto_rawDescGZIP() []byte {
	file_proto_edgeencoder_v1_edgeencoder_proto_rawDescOnce.Do(func() {
		file_proto_edgeencoder_v1_edgeencoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_edgeencoder_v1_edgeencoder_proto_rawDesc), len(file_proto_edgeencoder_v1_edgeencoder_proto_rawDesc)))
	})
	return file_proto_edgeencoder_v1_edgeencoder_proto_rawDescData
}

var file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_edgeencoder_v1_edgeencoder_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: edgeencoder.v1.StatusRequest
	(*StatusResponse)(nil), // 1: edgeencoder.v1.StatusResponse
}
var file_proto_edgeencoder_v1_edgeencoder_proto_depIdxs = []int32{
	0, // 0: edgeencoder.v1.EdgeEncoder.GetStatus:input_type -> edgeencoder.v1.StatusRequest
	1, // 1: edgeencoder.v1.EdgeEncoder.GetStatus:output_type -> edgeencoder.v1.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_edgeencoder_v1_edgeencoder_proto_init() }
func file_proto_edgeencoder_v1_edgeencoder_proto_init() {
	if File_proto_edgeencoder_v1_edgeencoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_edgeencoder_v1_edgeencoder_proto_rawDesc), len(file_proto_edgeencoder_v1_edgeencoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_edgeencoder_v1_edgeencoder_proto_goTypes,
		DependencyIndexes: file_proto_edgeencoder_v1_edgeencoder_proto_depIdxs,
		MessageInfos:      file_proto_edgeencoder_v1_edgeencoder_proto_msgTypes,
	}.Build()
	File_proto_edgeencoder_v1_edgeencoder_proto = out.File
	file_proto_edgeencoder_v1_edgeencoder_proto_goTypes = nil
	file_proto_edgeencoder_v1_edgeencoder_proto_depIdxs = nil
}
