// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/edgeencoder/v1/edgeencoder.proto

package edgeencoderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeEncoder_GetStatus_FullMethodName = "/edgeencoder.v1.EdgeEncoder/GetStatus"
)

// EdgeEncoderClient is the client API for EdgeEncoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EdgeEncoder service exposes operational status of an edge encoder instance.
// The control plane probes this in place of the standard grpc.health.v1.Health
// protocol, matching the mediaengine convention.
type EdgeEncoderClient interface {
	// GetStatus returns the current operational state of the encoder.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type edgeEncoderClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeEncoderClient(cc grpc.ClientConnInterface) EdgeEncoderClient {
	return &edgeEncoderClient{cc}
}

func (c *edgeEncoderClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, EdgeEncoder_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeEncoderServer is the server API for EdgeEncoder service.
// All implementations must embed UnimplementedEdgeEncoderServer
// for forward compatibility.
//
// EdgeEncoder service exposes operational status of an edge encoder instance.
// The control plane probes this in place of the standard grpc.health.v1.Health
// protocol, matching the mediaengine convention.
type EdgeEncoderServer interface {
	// GetStatus returns the current operational state of the encoder.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedEdgeEncoderServer()
}

// UnimplementedEdgeEncoderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeEncoderServer struct{}

func (UnimplementedEdgeEncoderServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEdgeEncoderServer) mustEmbedUnimplementedEdgeEncoderServer() {}
func (UnimplementedEdgeEncoderServer) testEmbeddedByValue()                     {}

// UnsafeEdgeEncoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeEncoderServer will
// result in compilation errors.
type UnsafeEdgeEncoderServer interface {
	mustEmbedUnimplementedEdgeEncoderServer()
}

func RegisterEdgeEncoderServer(s grpc.ServiceRegistrar, srv EdgeEncoderServer) {
	// If the following call panics, it indicates UnimplementedEdgeEncoderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeEncoder_ServiceDesc, srv)
}

func _EdgeEncoder_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeEncoderServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeEncoder_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeEncoderServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeEncoder_ServiceDesc is the grpc.ServiceDesc for EdgeEncoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeEncoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edgeencoder.v1.EdgeEncoder",
	HandlerType: (*EdgeEncoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _EdgeEncoder_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/edgeencoder/v1/edgeencoder.proto",
}
